### ISSUE TITLE
Example of angular vite in a (nx) monorepo

### ISSUE THREAD

**Issue by thebspin** [yannbf/storybook-coverage-recipes#2]
Any chance of coming up with an example for this?
I've tried adapting it but had no real succes beyond Storybook lanching without any stories.

In our case we have different apps/libs that all have their own Storybook.
And one mayor Storybook that bundles all the files together.

Would love to get the speed and coverage of Vite!

**Comment by yannbf** [comment]
Hey @thebspin thanks for opening this issue. I unfortunately do not have time to invest in coming up with an example, but if you could create a minimal reproduction, I'm happy to continue on top of it. If you do that, please create an issue in the https://github.com/storybookjs/test-runner repo with as much details as you can. Thanks!
