### ISSUE TITLE
Example of nextjs in a (turbo) monorepo 

### ISSUE THREAD

**Issue by csonchen** [yannbf/storybook-coverage-recipes#3]
i got the wrong tips like this when i setup coverage config; my project is turbo monorepo used in @storybook/nextjs framework
![image](https://github.com/yannbf/storybook-coverage-recipes/assets/5915045/654ef321-2368-4a76-9ca4-da6638daaba9)

**Comment by yannbf** [comment]
Hey there, it's impossible to know what's going on in your project without having access to it.
You might need to tweak addon-coverage options to include files if they're coming from separate package directories: https://github.com/storybookjs/addon-coverage#configuring-the-addon

Also, please create an issue in the https://github.com/storybookjs/test-runner repo with as much detail as possible, and a minor reproduction if you can!
